agents:
  agent:
    replay_buffer_size: 1000000
    action_repeat: 1
    add_observation_noise: False
  mbrl_agent:
    train_batch_size: 5000
    train_interaction_steps: 2000
    episode_length: 1000
    warmup_timesteps: 5000
    policy: cem_mpc
    model: mlp_ensemble
    scale_features: True
