options:
  trainer_options:
    video_log_frequency: 10
    log_frequency: 1
    max_video_length: 150
    eval_interaction_steps: 100
    eval_episode_length: 10
    training_logger_params:
      fps: 28
  seed: 1
  train_iterations: 90
  agent: mbrl_agent
  environment: MbrlReacher7DOF


