options:
  trainer_options:
    video_log_frequency: 5
    log_frequency: 1
    max_video_length: 1000
    eval_interaction_steps: 25
    eval_episode_length: 25
    training_logger_params:
      fps: 28
  seed: 1
  train_iterations: 100
  agent: mbrl_agent
  environment: MbrlSafexp-PointSimpleGoal1-v0


