options:
  trainer_options:
    video_log_frequency: 5
    log_frequency: 5
    max_video_length: 1000
    eval_interaction_steps: 250
    eval_episode_length: 250
    training_logger_params:
      fps: 28
  seed: 1
  train_iterations: 25
  agent: mbrl_agent
  environment: MbrlSafexp-PointGoal0-v0


