options:
  trainer_options:
    video_log_frequency: 1
    log_frequency: 1
    max_video_length: 500
    eval_interaction_steps: 100
    eval_episode_length: 20
    training_logger_params:
      fps: 28
  seed: 1
  train_iterations: 5
  agent: mbrl_agent
  environment: MbrlSafexp-PointGoal1-v0


