policies:
  cem_mpc:
    horizon: 12
    iterations: 10
    objective: TODOYARDEN
    smoothing: 0.0
    n_samples: 150
    n_elite: 30
    particles: 5
    stddev_threshold: 0.25
  mppi_mpc:
    horizon: 10
    objective: TODOYARDEN
    n_samples: 1000
  random_shooting_mpc:
    horizon: 10
    objective: TODOYARDEN
    n_samples: 1000