policies:
  cem_mpc:
    horizon: 10
    iterations: 10
    objective: TODOYARDEN
    smoothing: 0.0
    n_samples: 150
    n_elite: 30
    particles: 5
    stddev_threshold: 0.25
    noise_stddev: 0.1
  random_shooting_mpc:
    horizon: 10
    objective: TODOYARDEN
    n_samples: 1000